//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// IntelliCAD.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_IntelliCADTYPE              130
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDR_MAIN_RIBBON                 307
#define IDD_DIALOG_INSPECTOR            310
#define IDD_DIALOG_LOGIN                312
#define IDB_LOGO_IMG                    320
#define IDB_RIBBON_CUSTOM_IMG           321
#define IDD_FORM_VIEW_LIGHTING          324
#define IDD_DIALOG_IMAGE_INFO           326
#define IDD_DIALOG_MANIP                327
#define IDB_RIBBON_IMG_PROC_PANEL       328
#define IDD_DIALOG_SLICE_VIEW_FILTER    329
#define IDD_DIALOG_SERVER_INTERACTION_INACTIVE 330
#define IDR_ACCELERATOR1                331
#define IDD_DIALOG_SERVER_INTERACTION_ACTIVE 331
#define IDD_DIALOG_LOG                  332
#define IDC_STATIC_GBOX_volInfo         1000
#define IDC_STATIC_GBOX_volSize         1001
#define IDC_STATIC_LABEL_volSizeX       1002
#define IDC_STATIC_LABEL_volSizeY       1003
#define IDC_STATIC_LABEL_volSizeZ       1004
#define IDC_STATIC_STEXT_volSizeX       1005
#define IDC_STATIC_STEXT_volSizeY       1006
#define IDC_STATIC_STEXT_volSizeZ       1007
#define IDC_STATIC_LABEL_volPath        1008
#define IDC_STATIC_STEXT_volPath        1009
#define IDC_BUTTON1                     1012
#define IDC_LOGINDLG_BUTTON_SIGN_IN     1012
#define IDC_MANIP_BUTTON_moveTo         1012
#define IDC_SERVER_ACTIVE_BUTTON_imgDownTest 1012
#define IDC_EDIT3                       1013
#define IDC_EDIT_ID                     1013
#define IDC_LOGINDLG_EDIT_ID            1013
#define IDC_EDIT4                       1014
#define IDC_LOGINDLG_EDIT_PW            1014
#define IDC_CHECK1                      1015
#define IDC_SLIDER1                     1016
#define IDC_BUTTON3                     1016
#define IDC_MANIP_BUTTON_initSlicingPoint 1016
#define IDC_EDIT1                       1017
#define IDC_STATIC_AMBIENT              1018
#define IDC_EDIT15                      1018
#define IDC_IMG_INFO_EDIT_memSizeW      1018
#define IDC_SLIDER4                     1019
#define IDC_BUTTON2                     1019
#define IDC_BUTTON_CLOSE                1019
#define IDC_EDIT16                      1019
#define IDC_IMG_INFO_EDIT_memSizeH      1019
#define IDC_SLIDER5                     1020
#define IDC_EDIT17                      1020
#define IDC_IMG_INFO_EDIT_memSizeD      1020
#define IDC_EDIT2                       1021
#define IDC_EDIT5                       1022
#define IDC_EDIT18                      1022
#define IDC_TAB1                        1022
#define IDC_INDICATOR_TAB               1022
#define IDC_INSPECTOR_TAB               1022
#define IDC_IMG_INFO_EDIT_memSizeT      1022
#define IDC_SLIDER2                     1023
#define IDC_EDIT19                      1023
#define IDC_MANIP_EDIT_slicingPointX    1023
#define IDC_SLIDER6                     1024
#define IDC_EDIT20                      1024
#define IDC_MANIP_EDIT_slicingPointY    1024
#define IDC_SLIDER7                     1025
#define IDC_EDIT21                      1025
#define IDC_MANIP_EDIT_slicingPointZ    1025
#define IDC_EDIT6                       1026
#define IDC_IMG_INFO_EDIT_imageName     1026
#define IDC_EDIT7                       1027
#define IDC_EDIT22                      1027
#define IDC_IMG_INFO_EDIT_volSizeW      1027
#define IDC_EDIT8                       1028
#define IDC_EDIT23                      1028
#define IDC_IMG_INFO_EDIT_volSizeH      1028
#define IDC_EDIT24                      1029
#define IDC_IMG_INFO_EDIT_volSizeD      1029
#define IDC_IMG_INFO_EDIT_spacingX      1030
#define IDC_IMG_INFO_EDIT_spacingY      1031
#define IDC_IMG_INFO_EDIT_spacingZ      1032
#define IDC_SLICE_VIEW_FILTER_chartView 1033
#define IDC_SERVER_ACTIVE_userId        1034
#define IDC_SLIDER3                     1035
#define IDC_SLIDER8                     1036
#define IDC_LOG_LISTBOX_log             1036
#define IDC_SLIDER9                     1037
#define IDC_EDIT9                       1038
#define IDC_EDIT10                      1039
#define IDC_EDIT11                      1040
#define IDC_STATIC_AMBIENT2             1041
#define IDC_SLIDER10                    1042
#define IDC_SLIDER11                    1043
#define IDC_SLIDER12                    1044
#define IDC_EDIT12                      1045
#define IDC_EDIT13                      1046
#define IDC_EDIT14                      1047
#define IDC_STATIC_AMBIENT3             1048
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_BUTTON_CLOUD                 32771
#define ID_BUTTON_LIGHT1                32772
#define ID_BUTTON_LIGHT3                32774
#define ID_BUTTON_LIGHT2                32787
#define ID_BUTTON_CONFIG                32788
#define ID_MAIN_RIBBON_VOLUME_FILTER    32790
#define ID_MAIN_RIBBON_SLICE_FILTER     32791
#define ID_BUTTON4                      32792
#define ID_BUTTON2                      32793
#define ID_LOGIN_SUCCESS                32794

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        332
#define _APS_NEXT_COMMAND_VALUE         32796
#define _APS_NEXT_CONTROL_VALUE         1037
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
